"""Schema definitions for app profile outputs."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class TimelineEntry(BaseModel):
    """One timeline node rendered on the App profile page."""

    time: str
    title: str
    sub: str = ""
    icon: str = "Database"
    color_token: str = "slate"


class MetricProgress(BaseModel):
    """Progress bar item shown on the right side of the App page."""

    label: str
    value: int
    text: str
    color_token: str = "blue"
    risk_level: str = "safe"


class RiskAssessment(BaseModel):
    """Multi-loan risk assessment used by both report and UI."""

    level: str = "unknown"
    lending_app_count: int = 0
    recent_7d_lending_apps: list[str] = Field(default_factory=list)
    recent_30d_lending_apps: list[str] = Field(default_factory=list)
    reasoning: str = ""


class FinancialMaturity(BaseModel):
    """Banking and employment maturity summary."""

    level: str = "unknown"
    has_bank_app: bool = False
    has_ewallet: bool = False
    has_gov_app: bool = False
    supporting_apps: list[str] = Field(default_factory=list)
    reasoning: str = ""


class ConsumptionProfile(BaseModel):
    """Consumption preference summary."""

    level: str = "unknown"
    preferred_categories: list[str] = Field(default_factory=list)
    reasoning: str = ""


class AppVisuals(BaseModel):
    """Visual data contract used directly by the page."""

    top_category: str = "unknown"
    installed_app_count: int = 0
    recent_install_count_30d: int = 0
    main_preference_share: int = 0
    chart_palette: list[str] = Field(
        default_factory=lambda: ["#3b82f6", "#06b6d4", "#6366f1", "#8b5cf6", "#0f172a"]
    )
    progress_metrics: list[MetricProgress] = Field(default_factory=list)
    progress_metric_explanations: list[dict[str, Any]] = Field(default_factory=list)


class AppInsight(BaseModel):
    """LLM-focused insight summary for the app panel."""

    summary: str = ""
    reasons: list[str] = Field(default_factory=list)
    labels: list[str] = Field(default_factory=list)


class ModelTrace(BaseModel):
    """Track whether the final app result came from a real LLM response."""

    mode: str = "unknown"
    used_llm: bool = False
    model_name: str = ""
    fallback_reason: str = ""


class AppProfileStructuredResult(BaseModel):
    """Structured output generated by app profile skill."""

    agent_name: str = "app_profile_agent"
    uid: str
    status: str = "ok"
    activity_level: str = "unknown"
    summary: str = ""
    report_markdown: str = ""
    evidence: dict[str, Any] = Field(default_factory=dict)
    metrics: dict[str, Any] = Field(default_factory=dict)
    tags: list[str] = Field(default_factory=list)
    risk_assessment: RiskAssessment = Field(default_factory=RiskAssessment)
    financial_maturity: FinancialMaturity = Field(default_factory=FinancialMaturity)
    consumption_profile: ConsumptionProfile = Field(default_factory=ConsumptionProfile)
    app_insight: AppInsight = Field(default_factory=AppInsight)
    model_trace: ModelTrace = Field(default_factory=ModelTrace)
    timeline: list[TimelineEntry] = Field(default_factory=list)
    visuals: AppVisuals = Field(default_factory=AppVisuals)
