"""Schema definitions for behavior profile outputs."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class RepaymentWillingness(BaseModel):
    """Repayment willingness sub-model."""

    level: str = "unknown"
    reasoning: str = ""
    confidence: float = 0.0


class ProductSensitivity(BaseModel):
    """Product sensitivity sub-model."""

    level: str = "unknown"
    reasoning: str = ""
    confidence: float = 0.0


class ChurnRisk(BaseModel):
    """Churn risk sub-model."""

    level: str = "unknown"
    reasoning: str = ""
    retention_signal_score: float = 0.0


class ContactPreference(BaseModel):
    """Contact preference sub-model."""

    best_channel: str = ""
    frequency_preference: str = "unknown"
    reasoning: str = ""


class BehaviorProfileStructuredResult(BaseModel):
    """Structured output generated by behavior profile skill."""

    agent_name: str = "behavior_profile_agent"
    uid: str
    status: str = "ok"
    engagement_level: str = "unknown"
    evidence: dict[str, Any] = Field(default_factory=dict)
    # DEPRECATED: Use sub-models (repayment_willingness, product_sensitivity, churn_risk) or top-level level fields instead.
    metrics: dict[str, Any] = Field(default_factory=dict)
    tags: list[str] = Field(default_factory=list)
    model_trace: dict[str, Any] = Field(default_factory=dict)
    # Top-level level fields for convenience (mirror sub-models for label_builder access).
    repayment_willingness_level: str = Field(default="unknown")
    product_sensitivity_level: str = Field(default="unknown")
    churn_risk_level: str = Field(default="unknown")
    # Nested sub-models (populated from decision_result by assembler).
    repayment_willingness: RepaymentWillingness = Field(default_factory=RepaymentWillingness)
    product_sensitivity: ProductSensitivity = Field(default_factory=ProductSensitivity)
    churn_risk: ChurnRisk = Field(default_factory=ChurnRisk)
    contact_preference: ContactPreference = Field(default_factory=ContactPreference)
    churn_root_cause: list[str] = Field(default_factory=list)

