"""Schema definitions for credit profile outputs."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class FinancialMaturity(BaseModel):
    """Financial maturity sub-model."""

    level: str = "unknown"
    reasoning: str = ""
    financial_history_years: int = 0
    avg_credit_utilization: str = ""


class DebtPressure(BaseModel):
    """Debt pressure sub-model."""

    level: str = "unknown"
    reasoning: str = ""
    total_debt_mxn: float = 0.0
    monthly_payment_mxn: float = 0.0
    avg_credit_utilization: str = ""
    debt_to_income_ratio: float = 0.0
    overdue_ratio: float = 0.0


class CreditStability(BaseModel):
    """Credit stability sub-model."""

    level: str = "unknown"
    reasoning: str = ""
    inquiry_sources_type: str = "unknown"
    inquiry_frequency: int = 0


class BorrowingUrgency(BaseModel):
    """Borrowing urgency sub-model."""

    level: str = "unknown"
    reasoning: str = ""
    confidence: float = 0.0


class CreditProfileStructuredResult(BaseModel):
    """Structured output generated by credit profile skill."""

    agent_name: str = "credit_profile_agent"
    uid: str
    status: str = "ok"
    risk_level: str = Field(default="unknown")
    evidence: dict[str, Any] = Field(default_factory=dict)
    # DEPRECATED: Use sub-models (financial_maturity, debt_pressure, credit_stability, borrowing_urgency) or top-level level fields instead.
    metrics: dict[str, Any] = Field(default_factory=dict)
    tags: list[str] = Field(default_factory=list)
    model_trace: dict[str, Any] = Field(default_factory=dict)
    # Top-level level fields for convenience (mirror sub-models for label_builder access).
    financial_maturity_level: str = Field(default="unknown")
    debt_pressure_level: str = Field(default="unknown")
    credit_stability_level: str = Field(default="unknown")
    borrowing_urgency_level: str = Field(default="unknown")
    # Nested sub-models (populated from decision_result by assembler).
    financial_maturity: FinancialMaturity = Field(default_factory=FinancialMaturity)
    debt_pressure: DebtPressure = Field(default_factory=DebtPressure)
    credit_stability: CreditStability = Field(default_factory=CreditStability)
    borrowing_urgency: BorrowingUrgency = Field(default_factory=BorrowingUrgency)

