"""Schema definitions for Ops Advice skill outputs."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ModelTrace(BaseModel):
    """Track whether the final result came from accepted LLM output."""

    mode: str = "unknown"
    used_llm: bool = False
    model_name: str = ""
    fallback_reason: str = ""


class OpsAdviceStructuredResult(BaseModel):
    """Structured output generated by the Ops Advice skill."""

    agent_name: str = "ops_advice_agent"
    uid: str
    status: str = "ok"
    segment: str = ""
    segment_name: str = ""
    collection_strategy: dict[str, Any] = Field(default_factory=dict)
    churn_warning: dict[str, Any] = Field(default_factory=dict)
    outreach_channel: dict[str, Any] = Field(default_factory=dict)
    retention_offer: dict[str, Any] = Field(default_factory=dict)
    churn_root_cause: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    explanation: dict[str, Any] = Field(default_factory=dict)
    model_trace: ModelTrace = Field(default_factory=ModelTrace)
