"""Schema definitions for Product Advice skill outputs."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class ModelTrace(BaseModel):
    """Track whether the final result came from accepted LLM output."""

    mode: str = "unknown"
    used_llm: bool = False
    model_name: str = ""
    fallback_reason: str = ""


class ProductAdviceStructuredResult(BaseModel):
    """Structured output generated by the Product Advice skill."""

    agent_name: str = "product_advice_agent"
    uid: str
    status: str = "ok"
    segment: str = ""
    segment_name: str = ""
    renewal_strategy: dict[str, Any] = Field(default_factory=dict)
    credit_line_action: dict[str, Any] = Field(default_factory=dict)
    rate_plan: dict[str, Any] = Field(default_factory=dict)
    recommended_channel: dict[str, Any] = Field(default_factory=dict)
    priority: str = ""
    tags: list[str] = Field(default_factory=list)
    explanation: dict[str, Any] = Field(default_factory=dict)
    model_trace: ModelTrace = Field(default_factory=ModelTrace)
